title: Web Analytics Tutorial
description: SER421 - Advanced Project
theme: just-the-docs

url: https://just-the-docs.github.io

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  note:
    color: yellow
  highlight:
    color: green
  warning:
    color: red

mermaid:
  version: "10.6.1"

ga_tracking: G-WK7V28V6RS
ga_tracking_anonymize_ip: true
